### ISSUE TITLE
凯迪拉克 qx好像跑不了

### ISSUE THREAD

**Issue by XXXGITHUB777** [panghujiajia/QuantumultX#1]
cookie一直获取失败

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by panghujiajia** [comment]
> cookie一直获取失败
> 
> <sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>
凯迪拉克有两个地方要cookie，商城是webview写的 ，跟app本身是两个cookie，商城的cookie是签到的，app的cookie是做每日任务的，你打开app提示一次获取cookie成功，还要点击商城再提示一次获取cookie成功，这样签到和做任务才都ok

**Comment by panghujiajia** [comment]
> cookie一直获取失败
> 
> <sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

![image](https://user-images.githubusercontent.com/76469156/211845308-2cab4fbe-6569-4441-bbdf-53fdc6114791.png)
我这一直是OK的，你再试试，不行再联系我

**Comment by waysup** [comment]
> > cookie一直获取失败
> > 
> > <sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>
> 
> ![image](https://user-images.githubusercontent.com/76469156/211845308-2cab4fbe-6569-4441-bbdf-53fdc6114791.png)
> 我这一直是OK的，你再试试，不行再联系我

签到没问题 但是完成任务这部分失败 报错如下

```

2023/11/10 21:30:57:276  <console>    [JS Console]: 
Error：
[object Object]
{"statusCode":401,"headers":{"Transfer-Encoding":"chunked","x-trace-id":"mycadillac-prod-06-10-^1699268435446^1504988","Content-Type":"application/json;charset=UTF-8","Connection":"keep-alive","Server":"nginx","Date":"Fri, 10 Nov 2023 13:30:57 GMT"},"bodyBytes":{},"body":"{\"resultCode\":\"401\",\"message\":\"Token Check Failed\",\"data\":{}}","status":401}

```

**Comment by panghujiajia** [comment]
> > > cookie一直获取失败
> > > 
> > > <sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>
> > 
> > ![image](https://user-images.githubusercontent.com/76469156/211845308-2cab4fbe-6569-4441-bbdf-53fdc6114791.png)
> > 我这一直是OK的，你再试试，不行再联系我
> 
> 签到没问题 但是完成任务这部分失败 报错如下
> 
> ```
> 
> 2023/11/10 21:30:57:276  <console>    [JS Console]: 
> Error：
> [object Object]
> {"statusCode":401,"headers":{"Transfer-Encoding":"chunked","x-trace-id":"mycadillac-prod-06-10-^1699268435446^1504988","Content-Type":"application/json;charset=UTF-8","Connection":"keep-alive","Server":"nginx","Date":"Fri, 10 Nov 2023 13:30:57 GMT"},"bodyBytes":{},"body":"{\"resultCode\":\"401\",\"message\":\"Token Check Failed\",\"data\":{}}","status":401}
> 
> ```

token失效了 打开mitm重新获取下token

**Comment by shubaoguai** [comment]
商场签到cookie可以获取，每日任务获取不到，还有不支持h2

**Comment by panghujiajia** [comment]
> 商场签到cookie可以获取，每日任务获取不到，还有不支持h2

在 我的 里面获取不到吗

**Comment by shubaoguai** [comment]
获取不到，樱花佬说一半坏了> > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> 
> 
> 
> 在 我的 里面获取不到吗

**Comment by shubaoguai** [comment]
> > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> 
> 
> 
> 在 我的 里面获取不到吗

准确来说是获取到了之后是无效的

**Comment by panghujiajia** [comment]
> > > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> > 
> > 
> > 
> > 在 我的 里面获取不到吗
> 
> 准确来说是获取到了之后是无效的

获取之后 手动运行一下刷新cookie的脚本

**Comment by shubaoguai** [comment]
> > > > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> > > 
> > > 
> > > 
> > > 在 我的 里面获取不到吗
> > 
> > 准确来说是获取到了之后是无效的
> 
> 获取之后 手动运行一下刷新cookie的脚本

没用的，早就坏了

**Comment by panghujiajia** [comment]
> > > > > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> > > > 
> > > > 
> > > > 
> > > > 在 我的 里面获取不到吗
> > > 
> > > 准确来说是获取到了之后是无效的
> > 
> > 获取之后 手动运行一下刷新cookie的脚本
> 
> 没用的，早就坏了

刷新cookie的脚本是没有反馈的，刷新完了再手动运行一下每日任务脚本

**Comment by shubaoguai** [comment]
> > > > > > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> > > > > 
> > > > > 
> > > > > 
> > > > > 在 我的 里面获取不到吗
> > > > 
> > > > 准确来说是获取到了之后是无效的
> > > 
> > > 获取之后 手动运行一下刷新cookie的脚本
> > 
> > 没用的，早就坏了
> 
> 刷新cookie的脚本是没有反馈的，刷新完了再手动运行一下每日任务脚本

刚才测试了一下，不行，还是获取不到

**Comment by shubaoguai** [comment]
> > > > > > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> > > > > 
> > > > > 
> > > > > 
> > > > > 在 我的 里面获取不到吗
> > > > 
> > > > 准确来说是获取到了之后是无效的
> > > 
> > > 获取之后 手动运行一下刷新cookie的脚本
> > 
> > 没用的，早就坏了
> 
> 刷新cookie的脚本是没有反馈的，刷新完了再手动运行一下每日任务脚本

qx测试了一下，也是一样

**Comment by panghujiajia** [comment]
> > > > > > > 商场签到cookie可以获取，每日任务获取不到，还有不支持h2
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 在 我的 里面获取不到吗
> > > > > 
> > > > > 准确来说是获取到了之后是无效的
> > > > 
> > > > 获取之后 手动运行一下刷新cookie的脚本
> > > 
> > > 没用的，早就坏了
> > 
> > 刷新cookie的脚本是没有反馈的，刷新完了再手动运行一下每日任务脚本
> 
> qx测试了一下，也是一样

GooodTimes加我微信
