### ISSUE TITLE
请问你用的青龙哪个版本呢

### ISSUE THREAD

**Issue by c92244** [panghujiajia/QuantumultX#10]
我的2.10.13版本，docker/overlay2目录下有个merged/ql这个目录会一直生成core文件，然后root/ql/db文件有时里面的app.db的内存也会一直涨，我不知道是不是青龙面板的版本没用对

**Comment by panghujiajia** [comment]
> 我的2.10.13版本，docker/overlay2目录下有个merged/ql这个目录会一直生成core文件，然后root/ql/db文件有时里面的app.db的内存也会一直涨，我不知道是不是青龙面板的版本没用对

这个不是青龙脚本
