### ISSUE TITLE
配置完成后必须要关闭Mitm吗？

### ISSUE THREAD

**Issue by VictorLee4ever** [panghujiajia/QuantumultX#14]
圈x屏蔽广告需要开启Mitm。
看到定时签到这块配置完成后要关闭Mitm，这是必须的步骤吗？为什么要关闭Mitm？

**Comment by panghujiajia** [comment]
> 圈x屏蔽广告需要开启Mitm。 看到定时签到这块配置完成后要关闭Mitm，这是必须的步骤吗？为什么要关闭Mitm？

打开只是为了解密获取参数，获取完了之后Mitm不是必须的，打开更费电

**Comment by VictorLee4ever** [comment]
> > 圈x屏蔽广告需要开启Mitm。 看到定时签到这块配置完成后要关闭Mitm，这是必须的步骤吗？为什么要关闭Mitm？
> 
> 打开只是为了解密获取参数，获取完了之后Mitm不是必须的，打开更费电

多谢，已star :)

**Comment by VictorLee4ever** [comment]
2024/08/18 00:08:31:589  <console>    [JS Console]: 

脚本应用：V2EX
脚本环境：quanx
2024/08/18 00:08:31:602  <console>    [JS Console]: 

url：

https://www.v2ex.com/mission/daily
2024/08/18 00:08:31:604  <console>    [JS Console]: 

headers：

{"Accept-Encoding":"gzip, deflate, br","Cookie":"V2EX_LANG=zhcn; V2EX_TAB=\"2|1:0|10:1723857034|8:V2EX_TAB|8:dGVjaA==|05a711b87242eac734dd2f610076f6d6fcc3f4198f4749006d726e0033399245\"; A2=\"2|1:0|10:1723857008|2:A2|48:ZWZlYmFjN2UtYmUxOS00NTc2LWE1MzAtMzdiNTRkMWVjMTdi|a8637d968b205c76fe30a32361d3d36bc0797a85b12955a8af3cfa86f1b9526d\"; PB3_SESSION=\"2|1:0|10:1723856397|11:PB3_SESSION|72:djJleDoyNDA2OmRhMTQ6MTUxZTo1MDAwOmQyOTQ6Zjg4NTo3YjI4OmU2Yzg6NzAyMzg3MDE=|352dd9ae07d6497c443bca7510503c725b9e242c2b5bd2df6c7f1887f3ad845d\"","Connection":"keep-alive","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Host":"www.v2ex.com","Accept-Language":"zh-CN,zh-Hans;q=0.9","Referer":"https://www.v2ex.com/mission/daily","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36"}
2024/08/18 00:08:31:605  <console>    [JS Console]: 

body：

{}
2024/08/18 00:08:32:840  <console>    [JS Console]: 

status：
2024/08/18 00:08:32:842  <console>    [JS Console]: 

body：



v2ex签到未成功，这是日志，哪里有问题吗？？

**Comment by VictorLee4ever** [comment]
我发现定时任务是可以的，主动执行不成功

**Comment by panghujiajia** [comment]
> 我发现定时任务是可以的，主动执行不成功

v2ex的签到好像是有特定时间的，所以我设置的是9点执行签到，你可以试试你手动签到的时间点在官网签到看看

**Comment by shubaoguai** [comment]
凯迪拉克那个本签到任务没啥问题，每日任务获取ck坏了，surge也不能开h2，否则获取不到ck

**Comment by panghujiajia** [comment]
> 凯迪拉克那个本签到任务没啥问题，每日任务获取ck坏了，surge也不能开h2，否则获取不到ck

#1
