### ISSUE TITLE
唯品会签到能不能告诉我下变量，我想在青龙面板上跑

### ISSUE THREAD

**Issue by yemingjkl** [panghujiajia/QuantumultX#3]

**Comment by panghujiajia** [comment]
你说的变量是指的什么变量？

可以看下唯品会文件夹里面的signin.js文件，里面有签到的方法实现

**Comment by yemingjkl** [comment]
> 你说的变量是指的什么变量？
> 
> 可以看下唯品会文件夹里面的signin.js文件，里面有签到的方法实现

比如这个signin.js是抓的cookie跑的吗？通过识别什么变量运行的，因为青龙面板里我还会跑很多脚本，所以是变量就是容易识别的如wphck=抓的cookie，另外cookie是整个cookie 还是其中某个数值，就像京东脚本一样，变量就是 cookie里的某个值export JD_COOKIE='pt_pin;pt_key'

**Comment by panghujiajia** [comment]
> > 你说的变量是指的什么变量？
> > 可以看下唯品会文件夹里面的signin.js文件，里面有签到的方法实现
> 
> 比如这个signin.js是抓的cookie跑的吗？通过识别什么变量运行的，因为青龙面板里我还会跑很多脚本，所以是变量就是容易识别的如wphck=抓的cookie，另外cookie是整个cookie 还是其中某个数值，就像京东脚本一样，变量就是 cookie里的某个值export JD_COOKIE='pt_pin;pt_key'

我把header和body都抓下来了，然后Authorization是通过签名方法算出来的，具体看这一块

``` js
const url = WPH_URL.replace('info', 'exec');
// 签到接口多一个这个参数
// actId=fJSwqhdrFME
const params = { ...WPH_BODY, actId: 'fJSwqhdrFME' };
const Authorization = sign.getSign(
    url.split('?')[0],
    params,
    WPH_HEADERS.Cookie
);
let body = '';
for (i in params) {
    body += `${i}=${params[i]}&`;
}
const myRequest = {
    url,
    method,
    headers: {
        ...WPH_HEADERS,
        Authorization
    },
    body
};
```

**Comment by yemingjkl** [comment]
所以我应该抓包之后在配置文件填写export WPH_URL  export WPH_BODY这两个值就可以跑了吗

**Comment by panghujiajia** [comment]
还有一个WPH_HEADERS

**Comment by xujinhui2015** [comment]
@yemingjkl  大佬，青龙脚本实现出来了吗？实现出来了分享下.....

**Comment by iarthit** [comment]
大佬出一个安吉星的青龙脚本吧
