### ISSUE TITLE
小白

### ISSUE THREAD

**Issue by ChangLink** [panghujiajia/QuantumultX#5]
请问下凯迪拉克的怎么部署到圈X，实在没研究明白

**Comment by ChangLink** [comment]
我部署上去了发现都用不了，好像接口更新了

**Comment by panghujiajia** [comment]
> 我部署上去了发现都用不了，好像接口更新了

https://github.com/panghujiajia/Scripts/tree/master/KDLK
这里有使用方法，我用的没问题，你确定cookie有获取成功吗

**Comment by ChangLink** [comment]
我更改了KDLK/Rewrite.conf里面获取cookie的接口可以正常使用了谢谢，还有个问题您会长期更新吗 因为我是车主，也在使用这个哈哈哈哈

**Comment by panghujiajia** [comment]
> 我更改了KDLK/Rewrite.conf里面获取cookie的接口可以正常使用了谢谢，还有个问题您会长期更新吗 因为我是车主，也在使用这个哈哈哈哈

我自己在用，会长期更新的，点个star吧

**Comment by ChangLink** [comment]
好的我通过邮件回复您的，明天给您点

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月28日 00:46 |
| 收件人 | panghujiajia/Scripts ***@***.***> |
| 抄送人 | aa506302738 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [panghujiajia/Scripts] 小白 (Issue #5) |

我更改了KDLK/Rewrite.conf里面获取cookie的接口可以正常使用了谢谢，还有个问题您会长期更新吗 因为我是车主，也在使用这个哈哈哈哈

我自己在用，会长期更新的，点个star吧
