### ISSUE TITLE
surge配置文件解析失败：规则必须以final结尾

### ISSUE THREAD

**Issue by guaguababba** [panghujiajia/QuantumultX#6]
凯迪拉克surge运行报错这个？小白求助

**Comment by panghujiajia** [comment]
是按照教程来的吗？

**Comment by guaguababba** [comment]
是的啊，导入之后，打开就提示这个![IMG_20240614_113606.jpg](https://github.com/panghujiajia/Scripts/assets/116450053/786ef731-e0db-4f1d-add8-63539ff81e8c)

**Comment by panghujiajia** [comment]
你这是把模块当配置文件给装了，应该在修改-> 模块 里面添加，选择安装新模块，填写模块地址：https://raw.githubusercontent.com/panghujiajia/Scripts/master/KDLK/Surge.sgmodule

**Comment by guaguababba** [comment]
谢谢大佬，可以了，添加成功了，我再研究下。
