### ISSUE TITLE
凯迪拉克的签到问题

### ISSUE THREAD

**Issue by c92244** [panghujiajia/QuantumultX#7]
商城更新了之后签到好像用不了，提示接口错误，我看了签到里面的链接，现在网页版进入不了商城页面，提示安装APP才能进到商城

**Comment by panghujiajia** [comment]
> 商城更新了之后签到好像用不了，提示接口错误，我看了签到里面的链接，现在网页版进入不了商城页面，提示安装APP才能进到商城

接口换了，我抽空会更新一下

**Comment by panghujiajia** [comment]
已修复，更新一下
